//
// Generated file, do not edit! Created by nedtool 5.0 from a22.msg.
//

#ifndef __A22_M_H
#define __A22_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>a22.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * message A22
 * {
 *     int priority;
 *     simtime_t timestamp;
 *     int gateIndex;
 * }
 * </pre>
 */
class A22 : public ::omnetpp::cMessage
{
  protected:
    int priority;
    ::omnetpp::simtime_t timestamp;
    int gateIndex;

  private:
    void copy(const A22& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const A22&);

  public:
    A22(const char *name=nullptr, int kind=0);
    A22(const A22& other);
    virtual ~A22();
    A22& operator=(const A22& other);
    virtual A22 *dup() const {return new A22(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
    virtual int getPriority() const;
    virtual void setPriority(int priority);
    virtual ::omnetpp::simtime_t getTimestamp() const;
    virtual void setTimestamp(::omnetpp::simtime_t timestamp);
    virtual int getGateIndex() const;
    virtual void setGateIndex(int gateIndex);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const A22& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, A22& obj) {obj.parsimUnpack(b);}


#endif // ifndef __A22_M_H

